// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/auth/forget_password/data/repos/forget_password_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam_app/features/auth/forget_password/api/datasources/remote/forget_password_remote_data_source_impl.dart'
    as _i5;
import 'package:online_exam_app/features/auth/forget_password/data/models/forget_password_response/forget_password_response.dart'
    as _i2;
import 'package:online_exam_app/features/auth/forget_password/data/models/reset_password_response/reset_password_response.dart'
    as _i3;
import 'package:online_exam_app/features/auth/forget_password/data/models/verify_otp_code_response/verify_otp_code_response.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForgetPasswordResponse_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponse {
  _FakeForgetPasswordResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponse_1 extends _i1.SmartFake
    implements _i3.ResetPasswordResponse {
  _FakeResetPasswordResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyOtpCodeResponse_2 extends _i1.SmartFake
    implements _i4.VerifyOtpCodeResponse {
  _FakeVerifyOtpCodeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgetPasswordRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordRemoteDataSourceImpl extends _i1.Mock
    implements _i5.ForgetPasswordRemoteDataSourceImpl {
  MockForgetPasswordRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ForgetPasswordResponse> forgetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#email: email}),
            returnValue: _i6.Future<_i2.ForgetPasswordResponse>.value(
              _FakeForgetPasswordResponse_0(
                this,
                Invocation.method(#forgetPassword, [], {#email: email}),
              ),
            ),
          )
          as _i6.Future<_i2.ForgetPasswordResponse>);

  @override
  _i6.Future<_i3.ResetPasswordResponse> resetPassword({
    required String? email,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #newPassword: newPassword,
            }),
            returnValue: _i6.Future<_i3.ResetPasswordResponse>.value(
              _FakeResetPasswordResponse_1(
                this,
                Invocation.method(#resetPassword, [], {
                  #email: email,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.ResetPasswordResponse>);

  @override
  _i6.Future<_i4.VerifyOtpCodeResponse> verifyOtpCode({
    required String? resetCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtpCode, [], {#resetCode: resetCode}),
            returnValue: _i6.Future<_i4.VerifyOtpCodeResponse>.value(
              _FakeVerifyOtpCodeResponse_2(
                this,
                Invocation.method(#verifyOtpCode, [], {#resetCode: resetCode}),
              ),
            ),
          )
          as _i6.Future<_i4.VerifyOtpCodeResponse>);
}
