name: online_exam_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Design
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3

  # Splash screen
  flutter_native_splash: ^2.4.7

  # State management
  flutter_bloc: ^9.1.1

  # navigation
  go_router: ^17.0.1

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # API requests
  dio: ^5.9.0
  retrofit: ^4.9.2

  # JSON serialization
  json_annotation: ^4.9.0

  # Local storage
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0

  # Lottie
  lottie: ^3.3.2

  equatable: ^2.0.7
  pinput: ^6.0.1
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation tools
  build_runner: ^2.5.4
  freezed: ^3.0.0
  freezed_annotation: ^3.0.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.7.1
  retrofit_generator: ^10.2.1
  flutter_gen_runner: ^5.9.0
  mockito: ^5.5.1
  test: ^1.26.2
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/


flutter_gen:
  output: lib/core/gen/
  integrations:
    lottie: true
    flutter_svg: true