sonar.projectKey=Ah-med-Yahia_flower_app
sonar.organization=ah-med-yahia
sonar.host.url=https://sonarcloud.io

sonar.sources=lib
sonar.tests=test
sonar.dart.coverage.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/.dart_tool/**,**/build/**,**/ios/**,**/android/**,**/linux/**,**/macos/**,**/windows/**,**/web/**