sonar.projectKey=Ah-med-Yahia_flower_app
sonar.organization=ah-med-yahia

sonar.sources=lib
sonar.tests=test
sonar.dart.coverage.reportPaths=coverage/lcov.info

# اختياري لكن مفيد لتجنب تحليل ملفات مش مهمة
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**,**/.dart_tool/**,**/build/**,**/ios/**,**/android/**,**/linux/**,**/macos/**,**/windows/**,**/web/**