// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/authentication/forget_password/domain/usecases/forget_password_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam_app/config/base_response/base_response.dart' as _i2;
import 'package:online_exam_app/features/authentication/forget_password/domain/entities/forget_password_entity.dart'
    as _i5;
import 'package:online_exam_app/features/authentication/forget_password/domain/entities/reset_password_entity.dart'
    as _i7;
import 'package:online_exam_app/features/authentication/forget_password/domain/entities/verify_otp_code_entity.dart'
    as _i6;
import 'package:online_exam_app/features/authentication/forget_password/domain/repositories/forget_password_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgetPasswordRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordRepo extends _i1.Mock
    implements _i3.ForgetPasswordRepo {
  MockForgetPasswordRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseResponse<_i5.ForgetPasswordEntity>> forgetPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#email: email}),
            returnValue:
                _i4.Future<_i2.BaseResponse<_i5.ForgetPasswordEntity>>.value(
                  _FakeBaseResponse_0<_i5.ForgetPasswordEntity>(
                    this,
                    Invocation.method(#forgetPassword, [], {#email: email}),
                  ),
                ),
          )
          as _i4.Future<_i2.BaseResponse<_i5.ForgetPasswordEntity>>);

  @override
  _i4.Future<_i2.BaseResponse<_i6.VerifyOtpCodeEntity>> verifyOtpCode({
    required String? resetCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtpCode, [], {#resetCode: resetCode}),
            returnValue:
                _i4.Future<_i2.BaseResponse<_i6.VerifyOtpCodeEntity>>.value(
                  _FakeBaseResponse_0<_i6.VerifyOtpCodeEntity>(
                    this,
                    Invocation.method(#verifyOtpCode, [], {
                      #resetCode: resetCode,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.BaseResponse<_i6.VerifyOtpCodeEntity>>);

  @override
  _i4.Future<_i2.BaseResponse<_i7.ResetPasswordEntity>> resetPassword({
    required String? email,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #newPassword: newPassword,
            }),
            returnValue:
                _i4.Future<_i2.BaseResponse<_i7.ResetPasswordEntity>>.value(
                  _FakeBaseResponse_0<_i7.ResetPasswordEntity>(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #email: email,
                      #newPassword: newPassword,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.BaseResponse<_i7.ResetPasswordEntity>>);
}
